version: "3.9"
services:
  backend:
    build: ./backend
    container_name: laravel-app
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: top5
      DB_USERNAME: user
      DB_PASSWORD: secret

  frontend:
    build: ./frontend
    container_name: react-app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: top5
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
