version: "3.8"
services:
  backend:
    build: ./backend
    container_name: top5-backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=top5_db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: top5-frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: top5-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: top5_db
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
