services:
  backend:
    build: ./backend
    container_name: laravel-app
    volumes:
      - ./backend:/var/www
    expose:
      - "9000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: top5
      DB_USERNAME: user
      DB_PASSWORD: secret

  frontend:
    build: ./frontend
    container_name: react-app
    volumes:
      - ./frontend:/app
      - /app/node_modules # Garante que node_modules é do container, não do host
    ports:
      - "3000:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:9000/api

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: top5
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  backend-test:
    build: ./backend
    container_name: laravel-test
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    command: ["composer", "test"]
    environment:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: memory
    depends_on:
      - db

  frontend-test:
    build: ./frontend
    container_name: react-test
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "test", "--", "--watchAll=false"]
    environment:
      - CI=true
    depends_on:
      - backend
volumes:
  dbdata:
